### ISSUE TITLE
BarCodes.Instance is null in IOS

### ISSUE THREAD

**Issue by attrib75** [aritchie/barcodes#1]
This works in Windows Phone, but in IOS, the barcodeview.xaml throws BarCodes.Instance is null.  I'm calling  BarCodes.Init(); in FinishedLaunching.  Is there anything else I have to do?

**Comment by aritchie** [comment]
Works fine for me.  I don't have a barcodeview.xaml in the sample project here.

**Comment by attrib75** [comment]
My bad, that was my view.  I'm trying to implement this in my own project how it is in the sample.  As far as I understand, I add the dll and call  BarCodes.Init(); in FinishedLaunching in IOS.  I've done this, and created a view with a constructor just like the sample.  

 public BarcodeView() {
            var btnScan = new Button { Text = "Scan BarCode" };
            btnScan.Clicked += async (sender, args) => {
                var result = await BarCodes.Instance.Read();
                if (!result.Success)
                    await this.DisplayAlert("Failed", "Failed to get barcode", "OK");

                else {
                    var msg = String.Format("Barcode: {0} - {1}", result.Format, result.Code);
                    await this.DisplayAlert("Success", msg, "OK");
                }
            };

Barcodes.Instance is null in IOS but not in Windows Phone.  Not sure what's different.
thank you

**Comment by aritchie** [comment]
Is your iOS project a classic project?  The libraries I have only support the unified api.

**Comment by attrib75** [comment]
Oh snap.  I missed that.  Ok thanks for your help!
