### ISSUE TITLE
iOS issue while calling Init()

### ISSUE THREAD

**Issue by pkovacevic** [aritchie/barcodes#10]
Hi,

I downloaded the latest BarCodes version (3.0.8) using Nuget and I added BarCodes.Init() call in the AppDelegate class.
The call says the method is obsolete - You must call the Init() method from the platform project, not this PCL version.

It seems it doesn't recognize my iOS project as it should. It is a regular iOS universal project added with Xamarin.Forms template. Build symbols were MOBILE and IOS, which doesn't include the one I see in the source - UNIFIED. I tried later adding UNIFIED to the projects conditional compilation symbols but without success (i guess this should have nothing to do with the nuget worklfow anyway).

Any ideas?

Thanks

**Comment by aritchie** [comment]
You can't just install the Nuget package into the pcl.  You have to install them into the iOS project as well.

**Comment by pkovacevic** [comment]
Of course, I added the nuget package to the iOS project. It seems as it doesn't recognize the project because it labels it as a PCL
![issue](https://cloud.githubusercontent.com/assets/928809/8280354/db459824-18dc-11e5-8ede-0ab4ddfd65ae.png)

**Comment by aritchie** [comment]
Are you using a classic ios project?  I only release support for unified.
