### ISSUE TITLE
ClassNotFoundException on Android. PCL project

### ISSUE THREAD

**Issue by rayeckel** [aritchie/barcodes#11]
I receive the following error on Android when calling ' await BarCodes.Instance.Read()':

" java.lang.ClassNotFoundException: md5e1d4744ef128cd013cac92521f1a8e76.ZxingActivity "

The scanner works fine on WinPhone, and the bar code creator works fine on both. I have followed the code examples by placing the following line in my Android projects 'MainActivity/OnCreate':

BarCodes.Init(() => (Activity)Forms.Context);

My project is a Xamarin Forms project using a PCL and an individual project for each platform (iOS, Droid, WinPhone)

Any help would be greatly appreciated.

Thanks.

**Comment by rayeckel** [comment]
I got it working by putting the Init call into a custom renderer.

**Comment by aritchie** [comment]
That doesn't make any sense.  It was likely a botched nuget install.  It looks like zing.net.mobile wasn't installed
