### ISSUE TITLE
Scanner indefinitely loads on iOS

### ISSUE THREAD

**Issue by tVoss** [aritchie/barcodes#14]
I am calling await BarCodes.Instance.Read() to achieve a BarCodeResult in the middle of my app, and on Android this works fine. However, occasionally on iOS (usually the first time after deployment) attempting to read a barcode will result in the camera attempting to open, but never successfully complete.

Is this a known issue or am I simply doing something wrong with my implementation?

I am using a 32GB iPhone 5 for development purposes.

**Comment by aritchie** [comment]
I'm going to need a lot more details.  Is there any background warning?  Are you using Xamarin.forms?  What version of zxing.net.mobile is installed (1.5 came out yesterday and it is more like a 2.0 so I haven't touched it yet)?  Are you awaiting the result?  Can you supply a sample?

**Comment by tVoss** [comment]
I am using Xamarin.Forms, zxing.net version 1.4.7.1, and awaiting the result. The code I'm using is pretty straight forward, nothing too fancy:

    var res = await BarCodes.Instance.Read();
    if (!res.Success) return; // Scan was canceled
    ...

I'll check for background warnings next time I have access to the Mac dev box.

**Comment by aritchie** [comment]
I'm actually more interested in the code around the barcode call.  Is the call within an async void?  Is the task that this sits in also being awaited?

**Comment by tVoss** [comment]
Yes the call is within an async void triggered by pressing a button, although I believe I figured out what's causing the issue. When I unplug the iPhone from the computer while the xamarin debugger is still attached it causes all kinds of unexpected behavior, including the problem I was having with the scanner. Feel free to close this ticket unless you've found some other error in your investigation.
