### ISSUE TITLE
zxing.monoandroid.dll and zxing.ios.dll - Zxing.Net.Mobile 1.5.1

### ISSUE THREAD

**Issue by TorbenK** [aritchie/barcodes#15]
Hi,

I think you need to update to zxing.portable because in the new version(1.5.1) zxing.monoandroid and zxing.ios does no longer exists, which causes errors when updating Zxing.Net.Mobile.

<Reference Include="zxing.ios">
      <HintPath>..\packages\ZXing.Net.Mobile.1.4.7.1\lib\Xamarin.iOS\zxing.ios.dll</HintPath>
    </Reference>

<Reference Include="zxing.monoandroid">
      <HintPath>..\packages\ZXing.Net.Mobile.1.4.7.1\lib\MonoAndroid\zxing.monoandroid.dll</HintPath>
    </Reference>

**Comment by aritchie** [comment]
This library is no less Niger necessary with the latest zxing.net.mobile.  This was always nothing more than a pcl bridge, but zxing now supports that out of the box

**Comment by TorbenK** [comment]
Thank you for the response.

I just tried to update your source to compile against 1.5.1, and for some reason it seems like they made some changes to the Android implementation. The biggest thing is that I am missing the CustomOverlay property.  

Anyway I updated it for iOS and Android and pulled it here: https://github.com/TorbenK/barcodes

**Comment by brettcook99** [comment]
Hi aritchie,

For some reason I'm struggling getting zxing 1.5.1 to install on my pcl project.  Your package installed no problem.  It says the package does not support .NETPortable.

Any idea what I'm doing wrong?

Thanks,
-Brett

**Comment by aritchie** [comment]
Hi Brett 

You don't need this library anymore. Just use zxing.net.mobile
