### ISSUE TITLE
run time error in Windows Phone 

### ISSUE THREAD

**Issue by UdaraAlwisCMS** [aritchie/barcodes#5]
Hi aritchie,

You have done a great work with this library, keep it up. I implemented your library in a Xamarin Forms PCL project, there it worked well in Android and iOS but on Windows Phone it throws an invalid cross thread access exception.
I have created a simple test page and implemented the same code as your sample code here https://github.com/aritchie/barcodes/blob/master/src/Samples/Samples/Pages/MainPage.cs
I tried reading a bar code by clicking on the Bar code reading button, and then only this occurs on WP8 !
I have also called the BarCodes.Init(); method in my WP8 project MainPage.cs so I can not figure out the issue here. Please look into this issue.

Thank you.

![image](https://cloud.githubusercontent.com/assets/12168936/7390278/0a9d2394-ee94-11e4-87cf-5945ce833484.png)

**Comment by aritchie** [comment]
The first exception is what matters.  You haven't granted your app camera privileges

**Comment by UdaraAlwisCMS** [comment]
Thank you very much for your quick response. Now it works like a charm ! :)
