### ISSUE TITLE
[WP] Create gives Component not found

### ISSUE THREAD

**Issue by BladeMF** [aritchie/barcodes#6]
The problem is in ToImageStream. A code that works is:
var bm = writer.Write(cfg.BarCode);
var ms = new MemoryStream();
bm.SaveJpeg(ms, cfg.Width, cfg.Height, 0, 90);
ms.Seek(0, SeekOrigin.Begin);
return ms;

**Comment by aritchie** [comment]
Thanks.  Pushed to nuget
