### ISSUE TITLE
Can't call BarCodes.Init()

### ISSUE THREAD

**Issue by jfren484** [aritchie/barcodes#8]
I downloaded the nuget package and am trying to add `BarCodes.Init(() => (Activity)Forms.Context);` to my OnCreate method in my Android app. I get a compile error - "The name 'BarCodes' does not exist in the current context".

I've tried adding a using for `using Acr.BarCodes;` but that results in a compile error - "The type or namespace name 'BarCodes' does not exist in the namespace 'Acr' (are you missing an assembly reference?)"

I see the references in my project, but the assemblies listed are Acr.XamForms.BarCodeScanner and Acr.XamForms.BarCodeScanner.Droid. Neither of those assemblies appear to have a class called BarCodes in them, though.

**Comment by aritchie** [comment]
Acr.barcodes != acr.xamforms.barcodescanner

**Comment by jfren484** [comment]
@aritchie Sorry, I was confused because the nuget plugin for Acr.XamForms.BarCodeScanner links to this github repo. After some digging around, it looks to me like Acr.XamForms.BarCodeScanner has been replaced with Acr.BarCodes?

**Comment by aritchie** [comment]
correct

**Comment by jfren484** [comment]
If I could make a suggestion, then, I would recommend adding a note to your readme saying something like that (e.g. "If you came here from BarCodeScanner, it's been replaced with this..."). It might save someone else the confusion I had. :smile:
